# name: One Dark Pro Darker
# palette based on Binaryify/OneDark-Pro oneDarkProDarker

$base           = 0xff181a1f
$surface        = 0xff1e2227
$overlay        = 0xff23272e
$muted          = 0xff495162
$subtle         = 0xff7f848e
$text           = 0xffabb2bf
$bright         = 0xffd7dae0

$love           = 0xffe05561
$gold           = 0xffd19a66
$rose           = 0xffd18f52
$pine           = 0xff8cc265
$foam           = 0xff56b6c2
$iris           = 0xffc678dd
$blue           = 0xff61afef

$highlightLow   = 0xff1e2227
$highlightMed   = 0xff2c313a
$highlightHigh  = 0xff323842

general {
    col.active_border = rgba(d19a66ee) rgba(d19a66ee) rgba(c678ddee) rgba(c678ddee) rgba(c678ddee) rgba(61afefee) rgba(61afefee) rgba(61afefee) 90deg
    col.inactive_border = rgb(1e2227)
    gaps_in = 4
    gaps_out = 8
    border_size = 1
}

group {
    col.border_active = rgba(56b6c2dd)
    col.border_inactive = rgb(23272e)
}

decoration {
    rounding = 0
    rounding_power = 4

    blur {
        enabled = true
        size = 12
        passes = 1
        new_optimizations = true
        xray = true
        popups = false
    }

    active_opacity = 1.0
    inactive_opacity = 0.94
    fullscreen_opacity = 1.0
}

windowrule {
    name = windowrule-1
    border_color = $love
    match:fullscreen = 1
}
